FROM python:3.12

RUN apt update && apt install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    supervisor \
    git \
    && pip install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN mkdir /home/workspace

WORKDIR /home/workspace

# run supervisor
CMD ["/usr/bin/supervisord", "-n"]