version: '0.1.0'
name: 'jwt-test-project'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - dev_jwt_test
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - dev_jwt_test

  jwt_dev:
    build:
      context: .
      dockerfile: DockerFile
    container_name: jwt_dev
    ports:
      - 8000:8000
    volumes:
      - ./src/backend:/home/workspace
      - ./data/entrypoint.sh:/home/workspace/entrypoint.sh
      - ./data/supervisor_django.conf:/etc/supervisor/conf.d/supervisor_django.conf
      - ./data/uwsgi.ini:/data/uwsgi.ini
    depends_on:
      - redis
      - mariadb
    networks:
      - dev_jwt_test
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: "sh entrypoint.sh"

networks:
  dev_jwt_test:
    driver: bridge